export const SERVICE_CREATE_REQUEST = 'SERVICE_CREATE_REQUEST';
export const SERVICE_CREATE_SUCCESS = 'SERVICE_CREATE_SUCCESS';
export const SERVICE_CREATE_FAIL = 'SERVICE_CREATE_FAIL';
export const SERVICE_CREATE_RESET = 'SERVICE_CREATE_RESET';

export const SERVICE_DETAILS_REQUEST = 'SERVICE_DETAILS_REQUEST';
export const SERVICE_DETAILS_SUCCESS = 'SERVICE_DETAILS_SUCCESS';
export const SERVICE_DETAILS_FAIL = 'SERVICE_DETAILS_FAIL';

export const ALL_SERVICES_REQUEST = 'ALL_SERVICES_REQUEST';
export const ALL_SERVICES_SUCCESS = 'ALL_SERVICES_SUCCESS';
export const ALL_SERVICES_FAIL = 'ALL_SERVICES_FAIL';

export const UPDATE_SERVICE_REQUEST = 'UPDATE_SERVICE_REQUEST';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_RESET = 'UPDATE_SERVICE_RESET';
export const UPDATE_SERVICE_FAIL = 'UPDATE_SERVICE_FAIL';

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_RESET = 'DELETE_SERVICE_RESET';
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL';

export const GET_SERVICE_ITEM_REQUEST = 'GET_SERVICE_ITEMS_REQUEST';
export const GET_SERVICE_ITEM_SUCCESS = 'GET_SERVICE_ITEMS_SUCCESS';
export const GET_SERVICE_ITEM_FAIL = 'GET_SERVICE_ITEMS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
