export const ADD_TO_CART = 'SERVICE_ADD_TO_CART';
export const REMOVE_FROM_CART = 'SERVICE_REMOVE_FROM_CART';
export const EMPTY_CART = 'SERVICE_EMPTY_CART';

export const SAVE_SHIPPING_INFO = 'SERVICE_SAVE_SHIPPING_INFO';
